# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SupportWebRTC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SupportWebRTC
  pod 'Starscream', '~> 3.0.2'
  pod 'GoogleWebRTC'

  target 'SupportWebRTCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SupportWebRTCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
